# Pandas Notes (Python Data Analysis library)

Pandas is a Python Library used for :
- Data Manipulation
- Data analysis
- Handling structured data(tables, CSV, Excel....)

- import pandas as pd
- pd.Series(data, index = None, dtype = None, name = None,copy=False)
     - data -> list, array, dict, scalar
     - index -> labels for data, default 0,1,2,3,4...
     - dtype -> datatype
     - name -> name of series
     - copy -> True for copy data | False for reference original

In [31]:
import pandas as pd
# 1D array
# used for labeled indexing
data = pd.Series([10,20,30,40,50,60,70,80],name="sample_name") # -> Series not series
print(data)
print("Here with custom labels")
data1 = pd.Series([10,20,30,40,50,60,70,80],index = ['a','b','c','d','e','f','g','h'])
print(data1)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
Name: sample_name, dtype: int64
Here with custom labels
a    10
b    20
c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64

In [32]:
# Scalar value
# scalar value means In pandas, a scalar value refers to a single, indivisible data element rather than an array or sequence
s = pd.Series(5,index=['a','b','c'])
print(s)

a    5
b    5
c    5
dtype: int64

In [33]:
# Accesing data by index labl
data1['d']

np.int64(40)

In [34]:
data1['c':'h'] # Slicing

c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64

In [35]:
s = pd.Series([1,2,3,6,7],name="sample_name")
print(s * 2)
print(s + 10)

0     2
1     4
2     6
3    12
4    14
Name: sample_name, dtype: int64
0    11
1    12
2    13
3    16
4    17
Name: sample_name, dtype: int64

In [36]:
print(s.index)    # get index
print(s.values)    # get values (numpy array)
print(s.dtype)     # data type
print(s.shape)     # tuple representation of dimensions
print(s.size)      # returns int representing of total number of elements.

# number of elements

RangeIndex(start=0, stop=5, step=1)
[1 2 3 6 7]
int64
(5,)
5

- 2D array
- syntax : `df = pd.DataFrame(data, index=None, columns=None, dtype=None)`
    - index -> row labels
    - columns -> column names

In [37]:
dict_data = pd.Series({'a':10,'b':20,'c':30,'d':40},index = [10,2,30],name="With Dict")
print(dict_data) # in this case, index should match with dict keys

10   NaN
2    NaN
30   NaN
Name: With Dict, dtype: float64

In [38]:
data = {'Name': ['A', 'B'], 'Age': [20, 25]}
df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   25

#### Data input/output (File Handling) CSV
- Syntax : `df = pd.read_csv(filepath, sep=',', header=0, index_col=None)`
    - filepath : file path
    - sep -> delimiter
    - header -> row for column names
    - index_col -> set index column

- `pd.read_excel(filepath,sheet_name=0)`

- `pd.read_json(filepath)`

In [39]:
df = pd.read_csv("country_classification.csv")
df.head(10) #displays first n rows, default - 5

FileNotFoundError: [Errno 2] No such file or directory: 'country_classification.csv'

In [ ]:
df.tail(20) # displays last n rows

,country_code,country_label
238,WA,Wales
239,WF,Wallis and Futuna
240,WS,Samoa
241,XX,Not Stated
242,YE,Yemen
243,YT,Mayotte
244,ZA,South Africa
245,ZB,Ships' Bunkering
246,ZE,Destination Unknown - EU
247,ZM,Zambia
248,ZO,Destination Unknown - Non-EU
249,ZP,Passengers' Effects
250,ZS,Ships' Stores
251,ZW,Zimbabwe
252,TOT,Total
253,TOT (OMT CIF),Total goods - cost including insurance and fre...
254,TOT (OMT FOB),Total goods - free on board
255,TOT (OMT VFD),Total goods - value for duty
256,TOT (BoP basis),Total goods - Balance of Payments basis
257,BoP conceptual adjustment,Balance of Payments conceptual adjustment

In [ ]:
df.info() # structure of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country_code   257 non-null    object
 1   country_label  258 non-null    object
dtypes: object(2)
memory usage: 4.2+ KB

In [ ]:
df.describe() # statistics

                     country_code                              country_label
count                         257                                        258
unique                        257                                        258
top     BoP conceptual adjustment  Balance of Payments conceptual adjustment
freq                            1                                          1